### ISSUE TITLE
HWTs and Veterans

### ISSUE THREAD

**Issue by SergentSilver** [wargame-engine/grim-darkness#20]
First, for the Core units the option to give each squad simply says to "Add a ___ Weapon Team" as opposed to the normal Warhammer " two models in the unit may form a HWT".  This may not be in error, but I thought I'd point it out just in case as there is a significant difference between the two options. A side mention to this is that normally HWTs have their Lasguns (Defense Rifle) as well, to allow them to shoot with the rest of the squad normally if needed. 
Edit: The suggestion here is to change the HWT to replacing two Troopers to keep the squads at 10 bodies as well as add the Defense Rifle into the HWT gear. Also, since you are allowing HWTs in the Conscript squads and allowing Conscripts to have up to 20 additional bodies, it would make sense to allow a HWT per 10 bodies in the squad. So "Add Conscripted Weapon Team equipped with (Frag Grenades, Heavy Machinegun(1) [Front], Light CCW(2)) with specials (Crew(2)) for 18pts" would become something like "Add (Replace two Troopers with a) Conscripted Weapon Team equipped with (Frag Grenades, Heavy Machinegun(1) [Front], (Defense Rifle(2)?,) Light CCW(2)) with specials (Crew(2)) for 18pts. This can be done once for every 10 Troopers in the squad."

Second, again not necessarily a mistake, but the Veteran Sgt option to replace Defense Rifle with Pistol and Light CCW(2) being a greater discount to doing so on the regular Infantry seems strange as the gear on both sides of the equation is the same. As a side note on this one, there is currently no way in your datasheet to equip the Veteran Sgt with a Shotgun. To fix this, I suggest changing the "Replace any Veteran Trooper model Defense Rifle with Shotgun for 0pts each" to simply "Replace any Veteran model Defense Rifle with Shotgun for 0pts each". Alternatively, add it into the Sgt Ranged weapon options following my third suggestion. A leader with a Shotgun is seen on the old Cadian Lieutenant model. 
Edit: A benefit to making the Shotgun change general rather than changing the Sgt kit specifically is that it can then be applied to the HWT as well if you decide to give them Defense Rifles as per the first suggestion.

Third, more of a suggestion, but normally a Sgt model starts with a Laspistol and Chainsword (Pistol and Light CCW(2) here) and can then upgrade the Laspistol with a ranged weapon and the Chainsword with a melee weapon. I like your system as it is simple and makes sense, like allowing the Sgt to also have a Lasgun (Defense Rifle) and no dedicated melee weapon (Light CCW(1)), however it doesn't yet account for the possibility of having a Boltgun (Marine Rifle) and a CCW weapon. It is possible in Warhammer and appears on several models, such as Sgt "Ripper" Jackson, the old Catachan and Tallarn Lieutenants, and a few others I think. So what I'm suggesting is keeping the base kit of Defense Rifle and Light CCW(1) and reorganizing the Sgt weapons a bit into Ranged and Melee replacers. You could also try to fit in Hand Flamers somehow if you want, like is on the Valhallan Lieutenant and Commissar with Power Axe models.

For example:
-Replace Sergeant model Defense Rifle with a Pistol for -2pts, a Heavy Pistol for -1pts, (a Flamethrower Pistol for -1pts?,)  a Plasma Pistol for 3pts, (a Shotgun for 0pts,) or a Marine Rifle for 1pts.
-Replace Sergeant model Light CCW(1) with a Light CCW(2) for 1pts, an Energy Sword(2) for 5pts, an Energy Axe(2) for 7pts, an Energy Mace(2) for 9pts, or an Energy Fist(2) for 9pts.
Edit: I haven't yet seen a Hand Flamer equivalent in your datasheets, so I'm just calling it a Flamethrower Pistol to follow your apparent renaming philosophy, as well as guessing the points change based on the fact that Hand Flamers are just normal Flamers with a shorter range and the Pistol keyword in Warhammer.

I'm not yet sure how your whole point cost system works and which, if any of these, are intentional, so I don't feel confident in making these proposed changes myself.

**Comment by jaaimino** [comment]
To answer the heavy weapon team thing, currently we don't have a way to replace multiple models in the unit with something code wise. Atm I think just having it be an addon is a decent compromise. Most people will have the 10 models plus the weapon team anyway.

The veteran sgt replacing his weapons at a greater discount is accounting for him having a higher shoot skill so the weapon was worth more than it was on the normal squad. Adding the shotgun option to the sgt should be pretty easy. I'll add that swap in. If we make it any model you can technically replace the weapon team models with shotguns so it'll have to be specific to the sergeant. 

My philosophy on sgt weapons (across the board) is that it's easier to lay out all the options if they start with the lasgun first. Then they can choose to be a bit more melee focused (swapping for a pistol and melee weapon) or just swap the lasgun for a different rifle. Personally I would like players to choose between having the extra melee attack/getting the power fist etc or getting a better ranged weapon rather than just having both. It's also a bit odd to be able to just buy an extra melee attack.

We can chat in detail on this if you want though. I'm not entirely attached to it. Just feels a bit more natural if they have to give up the rifle for better melee. You couldn't really use a rifle and also fight with a chainsword anyway IMO. But I'm open to changing that stuff.

For now, let me add the shotgun as an option for the sgt and we'll go from there.
